# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='name',
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(default='', max_length=200, verbose_name='Brand Name'),
            preserve_default=False,
        ),
    ]
