# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 08:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0002_auto_20170422_1130'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=200, verbose_name='Brand Name')),
                ('color', models.CharField(max_length=200)),
                ('size', models.CharField(max_length=200)),
                ('vendor', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Product Price')),
                ('upddt', models.DateTimeField(verbose_name='date updated')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scraper_app.Product')),
            ],
        ),
    ]
