# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0003_competitor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='upddt',
        ),
    ]
