# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0004_auto_20170422_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(max_length=5),
        ),
    ]
