# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0006_productprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='prod',
            new_name='prod_key',
        ),
        migrations.RenameField(
            model_name='productprice',
            old_name='prod',
            new_name='prod_key',
        ),
        migrations.RemoveField(
            model_name='productprice',
            name='url',
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency',
            field=models.CharField(max_length=5, verbose_name='Currency'),
        ),
    ]
