# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 19:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0007_auto_20170422_2236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productprice',
            name='prod_key',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(default='GBP', max_length=5, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=12, verbose_name='Price'),
        ),
        migrations.DeleteModel(
            name='ProductPrice',
        ),
    ]
