# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0008_auto_20170422_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='upddt',
            field=models.DateTimeField(default='2017-04-22', editable=False, verbose_name='date updated'),
        ),
    ]
