# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0012_auto_20170422_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='price',
            field=models.DecimalField(decimal_places=2, default=-1, max_digits=10, verbose_name='Product Price'),
        ),
        migrations.AlterField(
            model_name='competitor',
            name='upddt',
            field=models.DateTimeField(default='2017-04-22 20:34:05', verbose_name='date updated'),
        ),
    ]
