# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0014_auto_20170422_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='upddt',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date updated'),
        ),
    ]
