# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0015_auto_20170422_2339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='competitor',
            old_name='upddt',
            new_name='update_dt',
        ),
    ]
