# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 20:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0016_auto_20170422_2347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='gtin',
        ),
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
