# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0017_auto_20170422_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
