# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-22 21:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraper_app', '0018_product_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitor',
            name='size',
        ),
    ]
